:Author: anion7
:Email: {AuthorEmail}
:Date: 16/03/2022
:Revision: version#
:License: Public Domain

= Project: Treadmill Software

Controll Teknic ServoMotors via an Arduino Mega 2560 and a graphical user interface facilitated via MATLAB

== Step 1: Installation
either download the source or copy the .m and .ino files into MATLAB and the Arduino IDE


== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact anion7 https://id.arduino.cc/anion7


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
